# Generated by Django 4.2.5 on 2023-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_password',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=5)),
                ('surname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('row', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
