# Generated by Django 4.2.5 on 2023-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_term', models.CharField(choices=[('1', '1'), ('2', '2'), ('Summer', 'Summer')], default='1', max_length=6)),
                ('course_year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], default=2023)),
                ('course_is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
