# Generated by Django 4.2.5 on 2023-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_class_of_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_of_students',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
