# Generated by Django 4.2.5 on 2023-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_amount',
            field=models.IntegerField(null=True),
        ),
    ]
