# Generated by Django 4.2.5 on 2023-09-24 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
