# Generated by Django 4.2.5 on 2023-09-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_student_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_amount',
            new_name='avilable_seat',
        ),
    ]
