# Generated by Django 4.2.5 on 2023-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_student_amount_course_avilable_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_is_open',
            field=models.BooleanField(),
        ),
    ]
