# Generated by Django 4.2.5 on 2023-09-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_course_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_is_open',
        ),
    ]
