# Generated by Django 4.2.5 on 2023-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_course_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_is_open',
            field=models.BooleanField(null=True),
        ),
    ]
