# Generated by Django 4.2.5 on 2023-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_course_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_class',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('student_surname', models.CharField(max_length=30)),
                ('student_lasname', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
    ]
