# Generated by Django 4.2.5 on 2023-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_of_students',
            fields=[
                ('course_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('student_id', models.CharField(max_length=10)),
                ('student_surname', models.CharField(max_length=30)),
                ('student_lasname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_class',
        ),
    ]
