# Generated by Django 4.2.5 on 2023-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_student',
            fields=[
                ('student_username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_surname', models.CharField(max_length=30)),
                ('student_lasname', models.CharField(max_length=30)),
            ],
        ),
    ]
