# Generated by Django 4.2.5 on 2023-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_student_info_delete_info_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
